import type { Metadata } from "next";
import Section from "@/components/Section";
import ProductCTA from "@/components/ProductCTA";
import SectionHeading from "@/components/SectionHeading";

export const metadata: Metadata = { title: "Custom Operational Software", description: "Purpose-built operational software for workflows that off-the-shelf systems cannot solve effectively.", alternates: { canonical: "/custom-solutions" } };
const steps = [["Understand", "Work with operational users to understand the problem, constraints and outcome."], ["Map", "Define the real workflow, roles, decisions, exceptions, information and integrations."], ["Design", "Shape a practical experience around the people who will use it in the office and field."], ["Build", "Develop the solution with structured data, clear ownership and maintainable architecture."], ["Implement", "Pilot with real users, support adoption and fit the software into the wider environment."], ["Iterate", "Improve the solution as operational use reveals better ways of working."]];
export default function CustomSolutionsPage() { return <main><Section className="pb-16 pt-16 lg:pb-24 lg:pt-24"><p className="eyebrow text-[#b94d21]">CUSTOM SOLUTIONS</p><h1 className="mt-5 max-w-5xl text-5xl font-semibold leading-[1.02] tracking-[-0.05em] sm:text-6xl">Operational problems do not always fit off-the-shelf software.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[#5b5952]">Valeron designs and builds software for important operational workflows that remain stuck between enterprise platforms, spreadsheets, email and manual handoffs.</p></Section>
  <section className="bg-[#171714] py-20 text-white"><Section><SectionHeading light eyebrow="HOW WE WORK" title="Start with the operation, then earn the software." /><div className="mt-12 grid gap-px overflow-hidden rounded-[1.7rem] border border-white/15 bg-white/15 md:grid-cols-2 lg:grid-cols-3">{steps.map(([title, text], index) => <article key={title} className="bg-[#171714] p-7"><p className="font-mono text-xs text-[#f1a27d]">0{index + 1}</p><h2 className="mt-5 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-white/60">{text}</p></article>)}</div></Section></section>
  <Section className="py-20 lg:py-28"><div className="grid gap-12 lg:grid-cols-2"><SectionHeading eyebrow="WHERE IT FITS" title="The operational layer between people and enterprise systems." description="A custom solution can structure a workflow without pretending to replace the ERP, document platform or data environment around it." /><div className="surface-card p-8"><p className="font-semibold">Typical starting points</p><ul className="mt-5 grid gap-3 text-sm text-[#5b5952]">{["Site-specific approvals and governance", "Maintenance and work requests", "Compliance and evidence capture", "Operational reporting and dashboards", "Structured data import and export", "Approved API and Microsoft ecosystem integration"].map((item) => <li key={item} className="flex gap-3"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-[#dd622d]" />{item}</li>)}</ul></div></div></Section><ProductCTA title="Bring us the workflow that does not fit." description="We’ll map the operational problem and identify whether the right path is Shunter, a focused product or a purpose-built solution." primary="Discuss your workflow" /></main>; }
