import type { Metadata } from "next";
import Section from "@/components/Section";
import ButtonLink from "@/components/ButtonLink";
import ProductScreenshot from "@/components/ProductScreenshot";
import ProductCTA from "@/components/ProductCTA";
import SectionHeading from "@/components/SectionHeading";
import { enterpriseCapabilities, shunterModules, shunterScreenshots } from "@/lib/site-data";

export const metadata: Metadata = { title: "Shunter Operational Management Platform", description: "One connected platform for assets, maintenance, workforce, compliance, scheduling, documents, inventory and operational reporting.", alternates: { canonical: "/shunter" }, openGraph: { title: "Shunter | One Connected Platform for Operational Work", description: "Connect assets, people and work in Valeron’s operational management platform.", url: "/shunter" } };

export default function ShunterPage() {
  const software = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Shunter", applicationCategory: "BusinessApplication", operatingSystem: "Web", description: "An operational management platform connecting assets, people and work.", publisher: { "@type": "Organization", name: "Valeron Pty Ltd" } };
  return <main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(software).replace(/</g, "\\u003c") }} />
    <Section className="pb-16 pt-14 sm:pt-20 lg:pb-24 lg:pt-24"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="eyebrow text-[#b94d21]">SHUNTER / BY VALERON</p><h1 className="mt-5 text-5xl font-semibold leading-[0.98] tracking-[-0.055em] sm:text-6xl">One connected platform for operational work.</h1><p className="mt-7 text-lg leading-8 text-[#5b5952]">Connect the assets, people, maintenance, compliance, schedules, documents and inventory behind complex operations—without losing the way your work actually happens.</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink href="/book-demo">Book a Shunter demo</ButtonLink><ButtonLink href="#platform" secondary>Explore the platform</ButtonLink></div></div><ProductScreenshot screenshot={shunterScreenshots[0]} priority /></div></Section>
    <section className="border-y border-black/10 bg-white/45 py-16"><Section><p className="mx-auto max-w-4xl text-center text-2xl font-medium leading-10 tracking-[-0.025em] sm:text-3xl">Operations do not happen in modules. A defect affects maintenance. Maintenance affects scheduling. Scheduling affects people, parts and documents. Shunter keeps that context connected.</p></Section></section>
    <Section className="py-20 lg:py-28" id="platform"><SectionHeading eyebrow="THE PLATFORM" title="A shared operational picture, organised around the work." description="Shunter’s product areas are connected by structured data, clear responsibility and operational history." /><div className="mt-16 space-y-20">{shunterModules.map((module, index) => <article key={module.title} className="grid gap-10 border-t border-black/15 pt-10 lg:grid-cols-2 lg:items-start"><div className={index % 2 ? "lg:order-2" : ""}><p className="font-mono text-xs tracking-[0.16em] text-[#b94d21]">{module.eyebrow}</p><h3 className="mt-5 text-3xl font-semibold tracking-[-0.035em]">{module.title}</h3><p className="mt-5 leading-7 text-[#66635b]">{module.description}</p></div><div className={`grid gap-2 sm:grid-cols-2 ${index % 2 ? "lg:order-1" : ""}`}>{module.capabilities.map((capability) => <div key={capability} className="surface-card flex items-center gap-3 px-5 py-4 text-sm font-medium"><span className="h-2 w-2 rounded-full bg-[#dd622d]" />{capability}</div>)}</div></article>)}</div></Section>
    <section className="bg-[#171714] py-20 text-white lg:py-28"><Section><SectionHeading light eyebrow="PRODUCT EXPERIENCE" title="Designed for the office, the workshop and the field." description="Shunter gives each part of the operation a focused view while keeping the underlying assets, people and work connected." /><div className="mt-14 grid gap-10 md:grid-cols-2">{shunterScreenshots.slice(1, 8).map((screenshot) => <ProductScreenshot key={screenshot.id} screenshot={screenshot} />)}</div><div className="mt-14 grid items-center gap-10 border-t border-white/15 pt-12 lg:grid-cols-[1fr_0.55fr]"><div><p className="eyebrow text-[#f1a27d]">FIELD EXPERIENCE</p><h3 className="mt-4 text-3xl font-semibold tracking-[-0.035em]">The operational record, where the work happens.</h3><p className="mt-5 max-w-xl leading-7 text-white/65">Operators can reach equipment details, controlled documentation and pre-start workflows without carrying the full desktop interface into the field.</p></div><ProductScreenshot screenshot={shunterScreenshots[8]} /></div></Section></section>
    <Section className="py-20 lg:py-28"><SectionHeading eyebrow="ENTERPRISE CAPABILITY" title="Built to become part of your operational architecture." description="Shunter is designed for controlled access, structured information and integration with the systems an organisation already relies on. Capability is configured and validated for each implementation." /><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{enterpriseCapabilities.map(([title, description]) => <article key={title} className="surface-card p-7"><h3 className="text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#66635b]">{description}</p></article>)}</div><div className="mt-12 border-l-2 border-[#dd622d] pl-6"><p className="max-w-3xl text-lg leading-8"><strong>Designed for integration:</strong> Shunter can be shaped to work alongside Microsoft Business Central, Microsoft Entra, enterprise data platforms and approved REST APIs. Specific integrations are confirmed during solution design.</p></div></Section>
    <ProductCTA title="See how Shunter can connect your operation." description="Bring the workflow, visibility gap or operational challenge. We’ll show you the relevant platform areas and discuss an implementation path." primary="Book a Shunter demo" />
  </main>;
}
