import type { Metadata } from "next";
import Link from "next/link";
import Section from "@/components/Section";
import ButtonLink from "@/components/ButtonLink";
import ProductScreenshot from "@/components/ProductScreenshot";
import ProductCTA from "@/components/ProductCTA";
import SectionHeading from "@/components/SectionHeading";
import ArrowUpRight from "@/components/ArrowUpRight";
import { enterpriseCapabilities, focusedSolutions, industries, shunterModules, shunterScreenshots } from "@/lib/site-data";

export const metadata: Metadata = { title: "Operational Software Built Around Real Work", description: "Valeron builds operational software connecting assets, people and work across mining, maintenance and complex industrial environments in Australia.", alternates: { canonical: "/" } };

export default function HomePage() {
  return <main>
    <Section className="pb-20 pt-14 sm:pt-20 lg:pb-28 lg:pt-24"><div className="grid items-end gap-12 lg:grid-cols-[1.08fr_0.92fr]">
      <div><p className="eyebrow text-[#b94d21]">AUSTRALIAN OPERATIONAL SOFTWARE</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[0.98] tracking-[-0.055em] sm:text-6xl lg:text-[5.35rem]">Operational software, built around the way work actually happens.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#5b5952] sm:text-xl">Valeron builds modern software that connects assets, people and work across complex industrial environments.</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink href="/shunter">Explore Shunter</ButtonLink><ButtonLink href="/book-demo" secondary>Book a demo</ButtonLink></div></div>
      <div className="lg:pb-2"><div className="border-l-2 border-[#dd622d] pl-6"><p className="font-mono text-xs uppercase tracking-[0.16em] text-[#747168]">From the field to a clear operational view</p><div className="mt-6 grid gap-3 sm:grid-cols-3 lg:grid-cols-1">{["Assets and maintenance", "Workforce and compliance", "Scheduling and execution"].map((item, index) => <div key={item} className="flex items-center gap-4 border-b border-black/10 pb-3"><span className="font-mono text-xs text-[#b94d21]">0{index + 1}</span><span className="font-medium">{item}</span></div>)}</div></div></div>
    </div></Section>
    <section className="bg-[#171714] py-20 text-white lg:py-28"><Section><div className="grid gap-12 lg:grid-cols-[0.75fr_1.25fr] lg:items-center"><div><p className="eyebrow text-[#f1a27d]">SHUNTER / FLAGSHIP PLATFORM</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">One connected platform for operational work.</h2><p className="mt-6 text-lg leading-8 text-white/65">Shunter brings the information behind assets, people, maintenance, scheduling, compliance, documents and inventory into a cohesive operational system.</p><div className="mt-8"><ButtonLink href="/shunter">See what Shunter manages</ButtonLink></div></div><ProductScreenshot screenshot={shunterScreenshots[0]} priority /></div></Section></section>
    <Section className="py-20 lg:py-28"><SectionHeading eyebrow="CONNECTED CAPABILITY" title="The work is connected. The software should be too." description="Instead of passing information between isolated systems and manual trackers, Shunter creates shared context across the operational areas that depend on each other." /><div className="mt-12 grid gap-px overflow-hidden rounded-[1.7rem] border border-[#dcd5c8] bg-[#dcd5c8] md:grid-cols-2 lg:grid-cols-5">{shunterModules.map((module) => <article key={module.title} className="bg-[#f7f3eb] p-6 lg:min-h-72"><p className="font-mono text-[10px] tracking-[0.15em] text-[#b94d21]">{module.eyebrow}</p><h3 className="mt-5 text-xl font-semibold tracking-tight">{module.eyebrow.split(" / ")[1]}</h3><p className="mt-3 text-sm leading-6 text-[#66635b]">{module.description}</p></article>)}</div></Section>
    <section className="border-y border-black/10 bg-white/45 py-20 lg:py-28"><Section><SectionHeading eyebrow="FOCUSED SOLUTIONS" title="Purpose-built software for specific operational problems." description="Valeron’s focused products remain available where a targeted workflow is the right answer. Shutdown Suite reflects the shutdown experience that shaped the broader platform direction." /><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{focusedSolutions.slice(0, 3).map((solution) => <Link key={solution.name} href={solution.href} className="group surface-card p-7 transition hover:-translate-y-1 hover:border-[#dd622d]/50"><p className="eyebrow text-[#747168]">{solution.category}</p><h3 className="mt-4 text-2xl font-semibold">{solution.name}</h3><p className="mt-3 leading-7 text-[#66635b]">{solution.description}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#b94d21]">Explore solution <ArrowUpRight /></span></Link>)}</div><Link href="/solutions" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[#b94d21] hover:underline">View all focused solutions <ArrowUpRight /></Link></Section></section>
    <Section className="py-20 lg:py-28"><div className="grid gap-12 lg:grid-cols-2"><SectionHeading eyebrow="OPERATIONAL CONTEXT" title="Built for environments where complexity is real." description="Valeron is particularly suited to organisations managing connected assets, people, compliance and operational work." /><div className="grid gap-3 sm:grid-cols-2">{industries.slice(0, 4).map((industry) => <div key={industry.name} className="border-b border-black/15 py-4"><h3 className="font-semibold">{industry.name}</h3><p className="mt-2 text-sm leading-6 text-[#66635b]">{industry.description}</p></div>)}</div></div><div className="mt-10"><ButtonLink href="/industries" secondary>Explore industries</ButtonLink></div></Section>
    <section className="bg-[#dd622d] py-20 text-white lg:py-24"><Section><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="eyebrow text-white/65">WHY VALERON</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.04em]">We understand the work before we design the software.</h2></div><div className="grid gap-6 sm:grid-cols-2"><p className="text-lg leading-8 text-white/85">Valeron grew from genuine experience in maintenance, shutdowns, planning, field execution, workforce coordination and operational reporting.</p><p className="text-lg leading-8 text-white/85">That context shapes practical workflows, clear information and software made for the people who run the work—not a generic process imposed from the outside.</p></div></div></Section></section>
    <Section className="py-20 lg:py-28"><SectionHeading eyebrow="ENTERPRISE DIRECTION" title="Serious operational software, designed to fit the wider environment." description="Shunter is designed as an operational layer alongside enterprise systems—not a claim to replace every platform already in place." /><div className="mt-12 grid gap-px overflow-hidden rounded-[1.7rem] border border-[#dcd5c8] bg-[#dcd5c8] md:grid-cols-2 lg:grid-cols-3">{enterpriseCapabilities.map(([title, description]) => <div key={title} className="bg-[#f7f3eb] p-7"><h3 className="font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#66635b]">{description}</p></div>)}</div></Section>
    <ProductCTA />
  </main>;
}
