import type { ScreenshotConfig } from "@/lib/site-data";

export const workforceEvidence = {
  request: { id: "workforce-request", label: "Workforce request and candidate matching", filename: "workforce-request.webp", kind: "desktop", aspectRatio: "1440 / 900", image: "/images/shunter/workforce-request.webp", description: "Shunter’s persisted workforce request view, captured in a test environment. All people and counts shown are synthetic examples, not customer results." },
  schedule: { id: "workforce-schedule", label: "Recorded workforce assignments", filename: "workforce-assignments.webp", kind: "desktop", aspectRatio: "768 / 650", image: "/images/shunter/workforce-assignments.webp", description: "Assignment detail from Shunter’s workforce calendar, cropped from a persisted test workflow. All people and clients are synthetic examples. This shows assignment visibility, not automated roster optimisation." },
} satisfies Record<string, ScreenshotConfig>;

export const metriczEvidence = {
  analysis: { id: "metricz-analysis", label: "Material analysis dashboard", filename: "analysis.webp", kind: "desktop", aspectRatio: "1440 / 1000", image: "/images/metricz/analysis.webp", description: "A synthetic example processed through Metricz’s real file-upload workflow. All figures are illustrative; the imported-data banner indicates the workflow, not real customer data. Reversal value is not verified savings." },
  mapping: { id: "metricz-mapping", label: "Uploaded workbook mapping", filename: "mapping.webp", kind: "desktop", aspectRatio: "1440 / 1000", image: "/images/metricz/mapping.webp", description: "Mapping an uploaded synthetic workbook: selected sheet, header row and explicit source columns. Captured from the real import workbench, not the fixture-only walkthrough." },
  validation: { id: "metricz-validation", label: "Validation and reconciliation", filename: "validation.webp", kind: "desktop", aspectRatio: "1440 / 1000", image: "/images/metricz/validation.webp", description: "Validation of the uploaded synthetic example, showing warnings, matched records and source references. Counts demonstrate the workflow and are not customer outcomes." },
  evidence: { id: "metricz-evidence", label: "Finding investigation and source evidence", filename: "evidence.webp", kind: "desktop", aspectRatio: "1440 / 1000", image: "/images/metricz/evidence.webp", description: "A finding from synthetic uploaded data, with contributing orders and source-row links. The imported-data banner does not indicate real customer data; transaction values are not savings." },
  reporting: { id: "metricz-reporting", label: "Excel review pack", filename: "reporting.webp", kind: "desktop", aspectRatio: "1440 / 1000", image: "/images/metricz/reporting.webp", description: "The report screen for the same synthetic import. The pack brings scoped findings, review information and source evidence together; no customer data is shown." },
} satisfies Record<string, ScreenshotConfig>;
