import type { Metadata } from "next";
import Section from "@/components/Section";
import ProductCTA from "@/components/ProductCTA";
import SectionHeading from "@/components/SectionHeading";
import { industries } from "@/lib/site-data";

export const metadata: Metadata = { title: "Industries", description: "Operational software for mining, heavy industry, field services, equipment operations, maintenance contractors and infrastructure.", alternates: { canonical: "/industries" } };
export default function IndustriesPage() { return <main><Section className="pb-16 pt-16 lg:pb-24 lg:pt-24"><p className="eyebrow text-[#b94d21]">INDUSTRIES</p><h1 className="mt-5 max-w-5xl text-5xl font-semibold leading-[1.02] tracking-[-0.05em] sm:text-6xl">For organisations where assets, people and operational work are inseparable.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[#5b5952]">Valeron is built for operating environments where the cost of fragmented information shows up in planning, compliance, maintenance and field execution.</p></Section>
  <section className="border-y border-black/10 bg-white/45 py-20 lg:py-28"><Section><div className="grid gap-px overflow-hidden rounded-[1.7rem] border border-[#dcd5c8] bg-[#dcd5c8] md:grid-cols-2 lg:grid-cols-3">{industries.map((industry, index) => <article key={industry.name} className="bg-[#f7f3eb] p-8 lg:min-h-64"><p className="font-mono text-xs text-[#b94d21]">0{index + 1}</p><h2 className="mt-6 text-2xl font-semibold">{industry.name}</h2><p className="mt-4 leading-7 text-[#66635b]">{industry.description}</p></article>)}</div></Section></section>
  <Section className="py-20 lg:py-28"><SectionHeading eyebrow="THE COMMON THREAD" title="Operational complexity—not an industry label—is the real fit." /><div className="mt-10 grid gap-5 md:grid-cols-3">{[["Connected work", "Asset, workforce and work information must move together."], ["Controlled execution", "Responsibilities, approvals and evidence need to remain clear."], ["Reliable visibility", "Operational leaders need current information without manual consolidation."]].map(([title, text]) => <article key={title} className="surface-card p-7"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-[#66635b]">{text}</p></article>)}</div></Section><ProductCTA title="Talk through your operational environment." description="We’ll focus on the work, constraints and information flows—not force your operation into a generic industry template." /></main>; }
